apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-php-front
  template:
    metadata:
      labels:
        app: my-php-front
    spec:
      containers:
      - name: my-php-front
        image: gcr.io/google-samples/gb-frontend:v4
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: GET_HOST_FROM
            value: dns
