apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec: 
  serviceName: prometheus
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccount: prometheus