---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
  POSTGRES_PASSWORD: dGVzdHBhc3N3b3JkCg==

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:10.13
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: testuser
          - name: POSTGRES_DB
            value: testdb
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        envFrom:
          - secretRef:
              name: postgres-secret
        volumeMounts:
          - name: postgres-vl
            mountPath: /var/lib/postgresql/data
    volumes:
        - name: postgres-vl
          persistentVolumeClaim:
              claimName: postgres-pvc