---
apiVersion: v1 
kind: Secret
metadata:
  name: redmine-secret
data:
  REDMINE_DB_PASSWORD: dGVzdHBhc3N3b3Jk
  REDMINE_SECRET_KEY_BASE: c3VwZXJzZWNyZXRrZXkK

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine-deployment
spec:
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - name: redmine
        image: redmine:4.1.1
        ports:
        - containerPort: 3000
        env:
          - name: REDMINE_DB_POSTGRES
            value: postgres-serv
          - name: REDMINE_DB_USERNAME
            value: testuser
          - name: REDMINE_DB_DATABASE
            value: testdb
        envFrom:
          - secretRef:
              name: redmine-secret
